### ISSUE TITLE
Network Analysis:  Error when creating a word network from bigrams

### ISSUE THREAD

**Issue by rccline** [juliasilge/tidytext-tutorial#6]
When running the code chunk to create a network analysis, I get an Error:  Contacting Delphi...the oracle is unavailable.
We apologize for any inconvenience.

I cannot find any help that I can understand regarding this error.

Thank you.

**Comment by juliasilge** [comment]
I think this error message is [an attempt at humor by the R authors](https://en.wikipedia.org/wiki/Pythia). 🤷‍♀️ 

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for how you are trying to create a network analysis? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by rccline** [comment]
The error occurred in eda.Rmd.   I discovered the error.  There was an  error in the code chunk to create bigram_graph object.  The error would not allow it to run.  This error threw a strange error message whose humor was totally lost on me.  

```
bigram_graph <- bigram_counts %>%
  filter(n > 5) %>%
 # as_tb               # incomplete code
  as_tbl_graph()   # corrected

bigram_graph
```
This issue is resolved.

**Comment by juliasilge** [comment]
I'm glad your error is resolved! And I certainly don't blame you about that attempt at humor. 🤨
